name             'aws_motd'
maintainer       'JamesJJ'
maintainer_email 'JamesJJ@users.noreply.github.com'
license          'MIT'
description      'Installs/Configures aws_motd'
long_description      'Installs/Configures aws_motd'
version          '0.1.1'
